LoadPackage("HAP");;
LoadPackage("IO");;
LoadPackage("SptSet");;
Read("res_space_group.g");;
Print("============================================================\n");;
Print("Benchmark: SG #10 (P2/m, C2h) ez FULL (classification + group structure)\n");;
Print("SPTSET_PARALLEL_JOBS = ", SPTSET_PARALLEL_JOBS, "\n");;
Print("SPTSET_PARALLEL_THRESHOLD = ", SPTSET_PARALLEL_THRESHOLD, "\n");;
Print("SPTSET_PHASE2_ENABLED = ", SPTSET_PHASE2_ENABLED, "\n");;
Print("============================================================\n");;
SG := SpaceGroupBBNWZ(3, 10);;
fSG := IsomorphismPcpGroup(SG);;
SG1 := Image(fSG);;
R := Resolution3DSpaceGroup(fSG, 7);;
Print("Resolution built.\n");;
gs := GeneratorsOfGroup(SG);;
f := GroupHomomorphismByImagesNC(SG1, GL(1, Integers),
    List(gs, x -> Image(fSG, x)), List(gs, x -> [[DeterminantMat(x)]]));;
SS := FermionEZSPTSpecSeq(R, f);;
t0 := NanosecondsSinceEpoch();;
FermionSPTLayersVerbose(SS, 3);;
t1 := NanosecondsSinceEpoch();;
Print("\nClassification done. Starting group structure...\n");;
M := SptSetSpecSeqResult(SS, 4, [1,2,3,4]);;
SptSetFpZModuleCanonicalForm(M);;
t2 := NanosecondsSinceEpoch();;
Print("\n============================================================\n");;
Print("RESULTS\n");;
Print("============================================================\n");;
Print("SPTSET_PARALLEL_JOBS = ", SPTSET_PARALLEL_JOBS, "\n");;
Print("LayersVerbose:  ", Int((t1-t0)/1000000), " ms\n");;
Print("SpecSeqResult:  ", Int((t2-t1)/1000000), " ms\n");;
Print("Total:          ", Int((t2-t0)/1000000), " ms\n");;
Print("Group structure: ");;
Display(M);;
SptSetPrintStats();;
FORCE_QUIT_GAP(0);
